"""Embedding generation via Ollama's local HTTP API.

LAYERING - this module must never import FastAPI, matching every other
services/ module. It talks to Ollama over HTTP rather than the database,
but deciding what text represents "the meaning of a transaction" and
turning it into a vector is business logic, not I/O plumbing, so it lives
in services/ rather than core/.
"""

import logging
from decimal import Decimal

import httpx

from app.core.config import get_settings

logger = logging.getLogger(__name__)


class EmbeddingError(Exception):
    """Raised when Ollama cannot produce an embedding.

    Deliberately not caught anywhere in this module. Whether a failed
    embedding should block the caller (e.g. transaction creation) or be
    logged and skipped differs by call site, so that decision belongs to
    the caller, not here.
    """


async def embed_text(text: str) -> list[float]:
    """Return the embedding vector for `text`, generated by Ollama.

    Raises:
        EmbeddingError: Ollama is unreachable, times out, or responds
            without a usable embedding.
    """
    settings = get_settings()
    try:
        async with httpx.AsyncClient(base_url=settings.OLLAMA_BASE_URL, timeout=30.0) as client:
            response = await client.post(
                "/api/embeddings",
                json={"model": settings.OLLAMA_EMBEDDING_MODEL, "prompt": text},
            )
            response.raise_for_status()
    except httpx.HTTPError as exc:
        raise EmbeddingError(f"Ollama embedding request failed: {exc}") from exc

    payload = response.json()
    embedding = payload.get("embedding")
    if not isinstance(embedding, list):
        raise EmbeddingError(f"Ollama response did not include an embedding: {payload}")
    return embedding


def build_transaction_embedding_text(
    *, description: str, amount: Decimal, category_name: str | None
) -> str:
    """Render a transaction as text for embed_text to turn into a vector.

    Shared by services/transaction.py (create) and
    services/transaction_import.py (CSV import) - the two write paths that
    create transactions - so the text a transaction is embedded with cannot
    drift between them.

    Includes the sign as a word ("expense"/"income") rather than a raw "-",
    and the category name when there is one - both are exactly the kind of
    thing a natural-language query in the future RAG chat (M11) would ask
    about ("what did I spend on groceries"), so they need to be in the text
    that gets embedded, not just sitting in adjacent columns.
    """
    kind = "expense" if amount < 0 else "income"
    text = f"{description}, {kind} of {abs(amount)}"
    if category_name is not None:
        text += f", category {category_name}"
    return text


async def embed_transaction_or_none(
    *, description: str, amount: Decimal, category_name: str | None
) -> list[float] | None:
    """Best-effort transaction embedding: on any failure, log and return
    None rather than raise.

    Ollama runs as a bare local process, not in docker-compose.yml, so it
    can be down without anyone noticing. transactions.embedding is nullable
    for exactly this reason - a transaction is fully valid without one, it
    simply will not surface in semantic search until a later backfill fills
    it in. Blocking transaction creation or CSV import on a local AI server
    being up would fail the app's core function over an optional
    enhancement.
    """
    text = build_transaction_embedding_text(
        description=description, amount=amount, category_name=category_name
    )
    try:
        return await embed_text(text)
    except EmbeddingError:
        logger.warning("Failed to embed transaction; continuing without one", exc_info=True)
        return None
