"""Embedding generation via Ollama's local HTTP API.

LAYERING - this module must never import FastAPI, matching every other
services/ module. It talks to Ollama over HTTP rather than the database,
but deciding what text represents "the meaning of a transaction" and
turning it into a vector is business logic, not I/O plumbing, so it lives
in services/ rather than core/.
"""

import httpx

from app.core.config import get_settings


class EmbeddingError(Exception):
    """Raised when Ollama cannot produce an embedding.

    Deliberately not caught anywhere in this module. Whether a failed
    embedding should block the caller (e.g. transaction creation) or be
    logged and skipped differs by call site, so that decision belongs to
    the caller, not here.
    """


async def embed_text(text: str) -> list[float]:
    """Return the embedding vector for `text`, generated by Ollama.

    Raises:
        EmbeddingError: Ollama is unreachable, times out, or responds
            without a usable embedding.
    """
    settings = get_settings()
    try:
        async with httpx.AsyncClient(base_url=settings.OLLAMA_BASE_URL, timeout=30.0) as client:
            response = await client.post(
                "/api/embeddings",
                json={"model": settings.OLLAMA_EMBEDDING_MODEL, "prompt": text},
            )
            response.raise_for_status()
    except httpx.HTTPError as exc:
        raise EmbeddingError(f"Ollama embedding request failed: {exc}") from exc

    payload = response.json()
    embedding = payload.get("embedding")
    if not isinstance(embedding, list):
        raise EmbeddingError(f"Ollama response did not include an embedding: {payload}")
    return embedding
