"""add category_id to transactions and budgets, backfilled

Revision ID: 94b480cc6d77
Revises: a6f87051f1e6
Create Date: 2026-08-31 13:36:00.000000

NOT AUTOGENERATED. Transaction and Budget's Python models still only
declare the old free-text `category` column at this point - the ORM cutover
is a later commit, deliberately separate from this migration (see that
commit's message for why). Autogenerate diffs models against the database,
so it has no way to propose a column no model declares yet.

WHAT THIS DOES, and why it's split from the next migration: this is purely
ADDITIVE. Both new `category_id` columns are nullable at the DB level -
even budgets', which will end up NOT NULL - and the old `category` string
columns are untouched. Nothing reads `category_id` yet, so this migration
is 100% safe to apply and just as safe to reverse: no application code's
behaviour depends on anything this migration changes. The NOT NULL
constraint, the new unique index, and dropping the old columns are a
separate, later migration, applied only once the application code has
already been cut over to reading/writing `category_id` - the standard
expand/contract shape for changing a live column without a moment where
code and schema disagree.

REVIEWED - this migration was read before being applied:
  - Both category_id columns are nullable=True at the DB level, matching
    the "purely additive" intent above - budgets.category_id becoming
    NOT NULL is deferred to the contract migration.
  - Both FKs carry ondelete="RESTRICT" - a database-level backstop behind
    the application's own in-use check in delete_category, matching the
    "the constraint is the actual guarantee" reasoning already used for
    Budget.category's uniqueness.
  - The backfill UPDATEs join on (user_id, lower(<old column>)) against
    categories, which the previous migration populated from exactly these
    same (user_id, lower(category)) pairs - every non-null category value
    is guaranteed a match.
  - transactions.category IS NULL rows are left with category_id = NULL,
    matching the column's own nullability (an uncategorized transaction
    stays valid).
  - downgrade() drops both indexes, both FKs, then both columns - the old
    `category` columns were never touched, so nothing else needs restoring.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94b480cc6d77"
down_revision: str | Sequence[str] | None = "a6f87051f1e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("transactions", sa.Column("category_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_transactions_category_id_categories"),
        "transactions",
        "categories",
        ["category_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_index(
        op.f("ix_transactions_category_id"), "transactions", ["category_id"], unique=False
    )
    op.execute(
        """
        UPDATE transactions t
        SET category_id = c.id
        FROM categories c
        WHERE c.user_id = t.user_id
          AND t.category IS NOT NULL
          AND lower(c.name) = lower(t.category)
        """
    )

    op.add_column("budgets", sa.Column("category_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_budgets_category_id_categories"),
        "budgets",
        "categories",
        ["category_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_index(op.f("ix_budgets_category_id"), "budgets", ["category_id"], unique=False)
    op.execute(
        """
        UPDATE budgets b
        SET category_id = c.id
        FROM categories c
        WHERE c.user_id = b.user_id
          AND lower(c.name) = lower(b.category)
        """
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_budgets_category_id"), table_name="budgets")
    op.drop_constraint(op.f("fk_budgets_category_id_categories"), "budgets", type_="foreignkey")
    op.drop_column("budgets", "category_id")

    op.drop_index(op.f("ix_transactions_category_id"), table_name="transactions")
    op.drop_constraint(
        op.f("fk_transactions_category_id_categories"), "transactions", type_="foreignkey"
    )
    op.drop_column("transactions", "category_id")
