"""add users table

Revision ID: a5ebde53b1a9
Revises: 8b721890e00d
Create Date: 2026-08-19 17:11:27.802090

REVIEW CHECKLIST - autogenerated migrations are a FIRST DRAFT:
  - A drop+add pair is usually a RENAME. Applied as generated, it destroys
    the column's data.
  - A new NOT NULL column on a populated table needs a server_default or a
    backfill, or the upgrade fails.
  - Autogenerate never emits data migrations, extensions, triggers, or views.
  - Confirm downgrade() actually reverses upgrade().

REVIEWED - this migration was read before being applied:
  - Creates one new table; no drop+add pair, so no rename is being masked.
  - The table is new and therefore empty, so the NOT NULL columns need no
    backfill.
  - Every constraint is explicitly NAMED by our naming convention
    (pk_users, uq_users_email, ck_users_email_lowercase), which is what makes
    downgrade() able to drop them deterministically.
  - No separate index on `email` is needed: PostgreSQL implements a UNIQUE
    constraint with an index, so adding one would duplicate it.
  - downgrade() drops the table, exactly reversing upgrade().

KNOWN AND ACCEPTED: `id` has no server-side default. UUIDs are generated in
Python by the ORM, so a hand-written `INSERT INTO users (...)` in psql that
omits `id` will fail. Every write goes through the ORM, so this is the
correct trade-off rather than installing pgcrypto/uuid-ossp for it.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5ebde53b1a9"
down_revision: str | Sequence[str] | None = "8b721890e00d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_lowercase")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
