"""finalize budgets and transactions category_id cutover

Revision ID: 0ec1045a71a2
Revises: 94b480cc6d77
Create Date: 2026-08-31 13:47:32.080419

REVIEW CHECKLIST - autogenerated migrations are a FIRST DRAFT:
  - A drop+add pair is usually a RENAME. Applied as generated, it destroys
    the column's data.
  - A new NOT NULL column on a populated table needs a server_default or a
    backfill, or the upgrade fails.
  - Autogenerate never emits data migrations, extensions, triggers, or views.
  - Confirm downgrade() actually reverses upgrade().

REVIEWED - this migration was read before being applied:
  - Not a drop+add pair masking a rename: budgets.category and
    transactions.category are DROPPED, not renamed - their replacement
    (category_id) was already added and fully backfilled in the previous
    migration (94b480cc6d77), so no data is lost by dropping them here.
  - budgets.category_id SET NOT NULL is safe: every budgets row has had
    category_id populated since the previous migration's backfill, which
    itself relied on every budget's category string having a matching
    categories row (guaranteed by the migration before THAT one,
    a6f87051f1e6, which populated categories from budgets first,
    unconditionally, before transactions).
  - uq_budgets_user_id_category_id replaces uq_budgets_user_id_category_lower
    correctly - a plain equality index, no func.lower() needed, since
    category_id already refers to one canonical Category row.
  - THE AUTOGENERATED downgrade() WAS WRONG AND HAS BEEN HAND-FIXED: the
    original draft re-added budgets.category as NOT NULL with no backfill,
    which fails outright against a populated table (PostgreSQL refuses a
    new NOT NULL column with no default unless the table is empty), and
    re-added transactions.category with no data restoration at all. Both
    are now re-added nullable, backfilled from category_id via the reverse
    join, and only then does budgets.category get its NOT NULL back.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ec1045a71a2"
down_revision: str | Sequence[str] | None = "94b480cc6d77"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("budgets", "category_id", existing_type=sa.UUID(), nullable=False)
    op.drop_index(op.f("uq_budgets_user_id_category_lower"), table_name="budgets")
    op.create_index(
        "uq_budgets_user_id_category_id", "budgets", ["user_id", "category_id"], unique=True
    )
    op.drop_column("budgets", "category")
    op.drop_column("transactions", "category")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Restore both string columns WITH their data, not just their shape.

    The autogenerated draft added `budgets.category` back as NOT NULL with
    no backfill - which fails outright against a populated table, since
    PostgreSQL refuses a new NOT NULL column with no default unless the
    table is empty - and added `transactions.category` back with no data
    restoration at all, silently losing every category assignment. Both
    columns are re-added nullable first, backfilled from category_id via
    the exact reverse of the forward migration's join, and only then does
    budgets.category get its NOT NULL back - after the backfill guarantees
    no row is left NULL.
    """
    op.add_column(
        "transactions",
        sa.Column("category", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.add_column(
        "budgets",
        sa.Column("category", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.execute(
        """
        UPDATE transactions t
        SET category = c.name
        FROM categories c
        WHERE c.id = t.category_id
        """
    )
    op.execute(
        """
        UPDATE budgets b
        SET category = c.name
        FROM categories c
        WHERE c.id = b.category_id
        """
    )
    op.alter_column("budgets", "category", existing_type=sa.String(length=100), nullable=False)
    op.drop_index("uq_budgets_user_id_category_id", table_name="budgets")
    op.create_index(
        op.f("uq_budgets_user_id_category_lower"),
        "budgets",
        ["user_id", sa.literal_column("lower(category::text)")],
        unique=True,
    )
    op.alter_column("budgets", "category_id", existing_type=sa.UUID(), nullable=True)
