"""add categories table

Revision ID: 20df522ef673
Revises: 93b55f74bb29
Create Date: 2026-08-31 13:20:53.979580

REVIEW CHECKLIST - autogenerated migrations are a FIRST DRAFT:
  - A drop+add pair is usually a RENAME. Applied as generated, it destroys
    the column's data.
  - A new NOT NULL column on a populated table needs a server_default or a
    backfill, or the upgrade fails.
  - Autogenerate never emits data migrations, extensions, triggers, or views.
  - Confirm downgrade() actually reverses upgrade().

REVIEWED - this migration was read before being applied:
  - Creates one new table; no drop+add pair, so no rename is being masked.
  - The table is new and therefore empty, so the NOT NULL columns (user_id,
    name) need no backfill. Populating it from the EXISTING free-text
    category values on transactions/budgets is deliberately a separate
    migration (the next one) - autogenerate cannot write a data migration,
    and mixing "create the table" with "backfill it" would make this
    migration's diff harder to review in isolation.
  - fk_categories_user_id_users carries ondelete="CASCADE", matching the
    model.
  - ix_categories_user_id is present (a foreign key does not create one on
    its own in PostgreSQL).
  - uq_categories_user_id_name_lower correctly compiled to a functional
    index on (user_id, lower(name)), same pattern already reviewed for
    uq_budgets_user_id_category_lower.
  - downgrade() drops both indexes then the table, exactly reversing upgrade().
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20df522ef673"
down_revision: str | Sequence[str] | None = "93b55f74bb29"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_categories_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    op.create_index(op.f("ix_categories_user_id"), "categories", ["user_id"], unique=False)
    op.create_index(
        "uq_categories_user_id_name_lower",
        "categories",
        ["user_id", sa.literal_column("lower(name)")],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_categories_user_id_name_lower", table_name="categories")
    op.drop_index(op.f("ix_categories_user_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
