"""populate categories from existing transaction and budget values

Revision ID: a6f87051f1e6
Revises: 20df522ef673
Create Date: 2026-08-31 13:31:21.128418

NOT AUTOGENERATED. Autogenerate diffs models against the database schema -
it has no concept of "read the data in these columns and turn it into rows
in a different table." This migration exists to do exactly that, by hand.

WHAT THIS DOES: `transactions.category` and `budgets.category` are still
free-text strings at this point (the FK cutover is later migrations). This
populates the new `categories` table with one row per distinct
(user, category name) pair currently in use, so a later migration can
backfill `category_id` columns by joining back to what this creates.

CANONICAL CASING: transactions and budgets may disagree on casing for what
matching (case-insensitive) treats as "the same" category - e.g. a budget
says "Groceries" while some transactions say "groceries". Budgets win first
(a budget's category is a deliberate, singular choice; a transaction's is
whatever was typed at entry time), then any transaction category not
already covered by a budget's casing.

REVIEWED - this migration was read before being applied:
  - Two INSERT ... SELECT DISTINCT ON passes, ordered by (user_id,
    lower(name)) so DISTINCT ON picks one deterministic row per
    case-insensitive group, not merely "whichever row postgres visits
    first".
  - The second pass's NOT EXISTS excludes any (user, name) already covered
    by the first pass's budget-derived rows, case-insensitively - this is
    what makes budgets' casing win.
  - gen_random_uuid() is PostgreSQL 13+ core (no extension needed) - this
    project runs PostgreSQL 17.
  - downgrade() is `DELETE FROM categories` - a full data backfill is not
    precisely reversible in general (there is no marker distinguishing
    "inserted by this migration" from "created via the API afterward"),
    but at the point this migration actually runs in this project's
    history, POST /categories has no real traffic yet, so a full delete is
    the correct reversal here. This is a genuine limitation of data
    migrations, not laziness - worth knowing, not hiding.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6f87051f1e6"
down_revision: str | Sequence[str] | None = "20df522ef673"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Populate categories from budgets first (authoritative casing), then
    from transactions for any (user, name) not already covered."""
    op.execute(
        """
        INSERT INTO categories (id, user_id, name, created_at, updated_at)
        SELECT gen_random_uuid(), b.user_id, b.category, now(), now()
        FROM (
            SELECT DISTINCT ON (user_id, lower(category)) user_id, category
            FROM budgets
            ORDER BY user_id, lower(category)
        ) b
        """
    )
    op.execute(
        """
        INSERT INTO categories (id, user_id, name, created_at, updated_at)
        SELECT gen_random_uuid(), t.user_id, t.category, now(), now()
        FROM (
            SELECT DISTINCT ON (user_id, lower(category)) user_id, category
            FROM transactions
            WHERE category IS NOT NULL
            ORDER BY user_id, lower(category)
        ) t
        WHERE NOT EXISTS (
            SELECT 1 FROM categories c
            WHERE c.user_id = t.user_id AND lower(c.name) = lower(t.category)
        )
        """
    )


def downgrade() -> None:
    """See the module docstring's REVIEWED note on why a full delete is the
    correct reversal at the point this migration actually runs."""
    op.execute("DELETE FROM categories")
