"""add budgets table

Revision ID: 93b55f74bb29
Revises: 793197cc3f68
Create Date: 2026-08-31 11:54:32.210065

REVIEW CHECKLIST - autogenerated migrations are a FIRST DRAFT:
  - A drop+add pair is usually a RENAME. Applied as generated, it destroys
    the column's data.
  - A new NOT NULL column on a populated table needs a server_default or a
    backfill, or the upgrade fails.
  - Autogenerate never emits data migrations, extensions, triggers, or views.
  - Confirm downgrade() actually reverses upgrade().

REVIEWED - this migration was read before being applied:
  - Creates one new table; no drop+add pair, so no rename is being masked.
  - The table is new and therefore empty, so the NOT NULL columns
    (user_id, category, limit_amount) need no backfill.
  - fk_budgets_user_id_users carries ondelete="CASCADE", matching the model.
  - ck_budgets_limit_amount_positive enforces limit_amount > 0 at the
    database level, not just in Pydantic - matches the model's
    CheckConstraint.
  - ix_budgets_user_id is present (a foreign key does not create one on its
    own in PostgreSQL).
  - uq_budgets_user_id_category_lower correctly compiled to a functional
    index on (user_id, lower(category)) rather than the literal columns -
    this is the one place autogenerate had to get an expression right, and
    it did: sa.literal_column("lower(category)") matches the model's
    func.lower(Budget.category).
  - downgrade() drops both indexes then the table, exactly reversing upgrade().
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93b55f74bb29"
down_revision: str | Sequence[str] | None = "793197cc3f68"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budgets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("limit_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("limit_amount > 0", name=op.f("ck_budgets_limit_amount_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_budgets_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budgets")),
    )
    op.create_index(op.f("ix_budgets_user_id"), "budgets", ["user_id"], unique=False)
    op.create_index(
        "uq_budgets_user_id_category_lower",
        "budgets",
        ["user_id", sa.literal_column("lower(category)")],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_budgets_user_id_category_lower", table_name="budgets")
    op.drop_index(op.f("ix_budgets_user_id"), table_name="budgets")
    op.drop_table("budgets")
    # ### end Alembic commands ###
