"""add refresh_tokens table

Revision ID: 3262551e3299
Revises: a5ebde53b1a9
Create Date: 2026-08-21 12:29:45.040258

REVIEW CHECKLIST - autogenerated migrations are a FIRST DRAFT:
  - A drop+add pair is usually a RENAME. Applied as generated, it destroys
    the column's data.
  - A new NOT NULL column on a populated table needs a server_default or a
    backfill, or the upgrade fails.
  - Autogenerate never emits data migrations, extensions, triggers, or views.
  - Confirm downgrade() actually reverses upgrade().

REVIEWED - this migration was read before being applied:
  - Creates one new table plus its two indexes; no drop+add pair, so no
    rename is being masked.
  - The table is new and therefore empty, so its NOT NULL columns need no
    backfill or server_default.
  - Every constraint is explicitly NAMED by our convention
    (pk_refresh_tokens, fk_refresh_tokens_user_id_users,
    ck_refresh_tokens_revocation_is_complete), so downgrade() can drop them
    deterministically.
  - Both indexes are deliberate, not incidental. A FOREIGN KEY does not
    create an index on the REFERENCING column in PostgreSQL, and every
    revocation query filters by user_id or family_id; without them, ending a
    session would be a sequential scan of every token ever issued.
  - ON DELETE CASCADE is carried through from the model, so deleting a user
    in psql cannot leave orphaned sessions behind.
  - downgrade() drops the indexes and then the table, exactly reversing
    upgrade(). Dropping the table alone would also remove the indexes; they
    are listed for symmetry and to keep the reversal explicit.

KNOWN AND ACCEPTED: nothing deletes expired rows. This table grows by one row
per login and one per refresh, forever. That is correct for now - the audit
trail is worth more than the disk - but it needs a pruning job before this is
a real production deployment.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3262551e3299"
down_revision: str | Sequence[str] | None = "a5ebde53b1a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(revoked_at IS NULL) = (revoked_reason IS NULL)",
            name=op.f("ck_refresh_tokens_revocation_is_complete"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"), "refresh_tokens", ["family_id"], unique=False
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    # ### end Alembic commands ###
