"""add goals table

Revision ID: 6dd2514c49bf
Revises: 0ec1045a71a2
Create Date: 2026-08-31 15:14:53.570453

REVIEW CHECKLIST - autogenerated migrations are a FIRST DRAFT:
  - A drop+add pair is usually a RENAME. Applied as generated, it destroys
    the column's data.
  - A new NOT NULL column on a populated table needs a server_default or a
    backfill, or the upgrade fails.
  - Autogenerate never emits data migrations, extensions, triggers, or views.
  - Confirm downgrade() actually reverses upgrade().

REVIEWED - this migration was read before being applied:
  - Creates one new table; no drop+add pair, so no rename is being masked.
  - The table is new and therefore empty, so the NOT NULL columns
    (user_id, category_id, target_amount) need no backfill.
  - fk_goals_user_id_users carries ondelete="CASCADE"; fk_goals_category_id_categories
    carries ondelete="RESTRICT" - both match the model.
  - ck_goals_target_amount_positive enforces target_amount > 0 at the
    database level, matching the model's CheckConstraint.
  - ix_goals_user_id and ix_goals_category_id are both present - a foreign
    key does not create an index on its own in PostgreSQL, and
    category_id needs its own index (not served by the composite unique
    below) for PostgreSQL to efficiently check the RESTRICT constraint.
  - uq_goals_user_id_category_id is a plain two-column unique index, no
    expression needed - category_id already refers to one canonical
    Category row.
  - downgrade() drops all three indexes then the table, exactly reversing
    upgrade().
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6dd2514c49bf"
down_revision: str | Sequence[str] | None = "0ec1045a71a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "goals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("target_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("target_amount > 0", name=op.f("ck_goals_target_amount_positive")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_goals_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_goals_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goals")),
    )
    op.create_index(op.f("ix_goals_category_id"), "goals", ["category_id"], unique=False)
    op.create_index(op.f("ix_goals_user_id"), "goals", ["user_id"], unique=False)
    op.create_index(
        "uq_goals_user_id_category_id", "goals", ["user_id", "category_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_goals_user_id_category_id", table_name="goals")
    op.drop_index(op.f("ix_goals_user_id"), table_name="goals")
    op.drop_index(op.f("ix_goals_category_id"), table_name="goals")
    op.drop_table("goals")
    # ### end Alembic commands ###
