"""add users.token_version

Revision ID: 703a00020abb
Revises: 3262551e3299
Create Date: 2026-08-21 13:19:35.072576

REVIEW CHECKLIST - autogenerated migrations are a FIRST DRAFT:
  - A drop+add pair is usually a RENAME. Applied as generated, it destroys
    the column's data.
  - A new NOT NULL column on a populated table needs a server_default or a
    backfill, or the upgrade fails.
  - Autogenerate never emits data migrations, extensions, triggers, or views.
  - Confirm downgrade() actually reverses upgrade().

REVIEWED - this migration was read before being applied:
  - One added column; no drop+add pair, so no rename is being masked.
  - The column is NOT NULL on a table that already has rows, which normally
    FAILS. It works here because server_default="1" backfills every existing
    row in the same statement. Removing that default would break the upgrade
    on any non-empty database - including production, but not a fresh CI
    database, which is exactly the kind of migration that passes CI and then
    fails where it matters.
  - Backfilling to 1 rather than 0 keeps the value meaningful: it is a
    version number, and every access token ever issued from now on carries
    one. Existing tokens carry no `ver` claim at all and are refused, which
    is intended - see the commit message.
  - downgrade() drops the column, exactly reversing upgrade(). It is
    genuinely lossy: rolling back discards every user's version counter, so
    tokens invalidated by a bump would become valid again. Acceptable for a
    counter, and worth knowing before running it.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "703a00020abb"
down_revision: str | Sequence[str] | None = "3262551e3299"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("token_version", sa.Integer(), server_default="1", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "token_version")
    # ### end Alembic commands ###
