"""add embedding column to transactions

Revision ID: ec2039619780
Revises: 6dd2514c49bf
Create Date: 2026-09-02 11:00:03.815191

REVIEW CHECKLIST - autogenerated migrations are a FIRST DRAFT:
  - A drop+add pair is usually a RENAME. Applied as generated, it destroys
    the column's data.
  - A new NOT NULL column on a populated table needs a server_default or a
    backfill, or the upgrade fails.
  - Autogenerate never emits data migrations, extensions, triggers, or views.
  - Confirm downgrade() actually reverses upgrade().

REVIEWED - this migration was read before being applied:
  - Adds one nullable column; no drop+add pair, so no rename is being
    masked, and nullable means the populated table needs no backfill or
    server_default.
  - Autogenerate did not (and cannot) emit the extension: pgvector's Vector
    type requires the `vector` extension to exist first, or add_column
    fails with "type vector does not exist". Added by hand below.
  - Autogenerate also missed the `pgvector.sqlalchemy` import entirely
    (silent NameError at import time, not caught until this file actually
    ran) - fixed by hand below too.
  - No ANN index (ivfflat/hnsw) yet - deliberately deferred to a follow-up
    migration once there's a realistic row count to tune it against. See
    Transaction.embedding's docstring in app/models/transaction.py.
  - downgrade() drops the column but deliberately leaves the extension
    installed: dropping it would fail loudly if any other table ever
    depends on it, and reinstalling it is a single cheap statement -
    asymmetric with upgrade() on purpose.
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec2039619780"
down_revision: str | Sequence[str] | None = "6dd2514c49bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column(
        "transactions",
        sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=768), nullable=True),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("transactions", "embedding")
