"""baseline empty schema

Revision ID: 8b721890e00d
Revises:
Create Date: 2026-08-18 16:55:52.358337

REVIEW CHECKLIST - autogenerated migrations are a FIRST DRAFT:
  - A drop+add pair is usually a RENAME. Applied as generated, it destroys
    the column's data.
  - A new NOT NULL column on a populated table needs a server_default or a
    backfill, or the upgrade fails.
  - Autogenerate never emits data migrations, extensions, triggers, or views.
  - Confirm downgrade() actually reverses upgrade().
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b721890e00d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass
